### ISSUE TITLE
How to run in a HPC cluster?

### ISSUE THREAD

**Issue by shenwei356** [citiususc/BigSeqKit#4]
Following the [guide](https://github.com/citiususc/BigSeqKit?tab=readme-ov-file#hpc-cluster-slurm-and-singularity ) .

> We assume that the cluster has installed Slurm and Singularity.

We do have them. 

However, the first step failed:

    ignis-deploy images singularity --host ignishpc/full ignis_full.sif
    DockerException:  Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

And the second step requires `docker`, which is not allowed and available. Our HPC administrators do not allow installing docker.

    docker run --rm -v $(pwd):/target ignishpc/slurm-submitter ignis-export /target

**Comment by cesarpomar** [comment]
Both cases require Docker to work, only that in the first step the ignis-deploy calls it and since it's not installed, it gives a "FileNotFoundError".

In any case, it's not necessary to perform the steps with Docker on the target cluster; they can be executed on a local computer and then the results can be copied to the cluster.

**Comment by shenwei356** [comment]
I tried again.

Unfortunately, binaries in `ignis/` folder  are not runnable, cause the mismatch of dynamic link libraries between local machine and clusters.

```
$ ./ignis-submit 
Error: dl failure on line 542
Error: failed /homes/shenwei/download/bigseqkit/ignis/backend/jre/lib/server/libjvm.so, because /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /homes/shenwei/download/bigseqkit/ignis/backend/jre/lib/server/libjvm.so)
```

**Comment by cesarpomar** [comment]
To use Slurm, you should use the script ``ignis-slurm``. However, since it will find the same issue, edit the script and change ``${IGNIS_HOME}/backend/jre/bin/java`` to just ``java`` so Java from the cluster will be used instead.

**Comment by shenwei356** [comment]
After installing `openjdk` with `conda`, finally, I can run the `ignus_slum`. While I can't find the stderror and stdout file like when I submit other slurm jobs.

```
$ ignis-slurm  01:00:00 ignis_full.sig 'bigseqkit seq'
Submitted batch job 62480067

$ squeue 
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          62455993  standard interact  shenwei  R    4:07:56      1 hl-codon-124-03
          62478557  standard interact  shenwei  R      12:48      1 hl-codon-114-03
        62480067+0     short    ignis  shenwei CG       0:00      1 
        62480067+1     short    ignis  shenwei CG       0:00      1 

$ ls
ignis  ignis_full.sif

```
